### ISSUE TITLE
Edit a command

### ISSUE THREAD

**Issue by smee** [jpmonettas/magic-sheet#1]
First of all, thank you for this tool! I didn't even know I wanted something like this :smile: 

Is there a way to edit an existing command? I have to remember (and keep forgetting) to copy the form before clicking OK just in case I have a typo.

**Comment by jpmonettas** [comment]
Hey great you find it useful! 

No way to edit commands yet but that is the next thing I'll add.

What I do is I use my normal repl to create the command and once it works as expected I create it in magic-sheet.

**Comment by jpmonettas** [comment]
https://github.com/jpmonettas/magic-sheet/commit/993001bdcfe95829d0909d235633ec628387be65 implements command edition!
